[bans]
multiple_versions = "deny"

[licenses]
unlicensed = "deny"
unknown = "deny"
allow = [
	"Apache-2.0",
	"BSD-2-Clause",
	"BSD-2-Clause-FreeBSD",
	"BSD-3-Clause",
	"BSL-1.0",
	"CC0-1.0",
	"ISC",
	"MIT",
	"MPL-2.0",
	"Unicode-DFS-2016",
	"Unlicense",
	"Zlib",
]
